#?? ??
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8


#server.port=8080
#server.servlet.context-path=/
#server.servlet.encoding.charset=UTF-8

#???? ??

spring:
  mvc:
    view:
      prefix: /WEB-INF/jblog/
      suffix: .jsp

#spring.mvc.view.prefix=/WEB-INF/jblog/
#spring.mvc.view.suffix=.jsp

